module.exports = {
  plugins: ['flowtype'],
  env: {
    es6: true,
  },
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
  },
  rules: {
    'flowtype/define-flow-type': 1,
    'flowtype/require-valid-file-annotation': 1,
    'flowtype/no-types-missing-file-annotation': 2,
    'flowtype/require-return-type': 0,
    'flowtype/space-after-type-colon': 0,
    'flowtype/space-before-generic-bracket': 0,
    'flowtype/space-before-type-colon': 0,
    'flowtype/type-id-match': 0,
    'flowtype/semi': 0,
    'flowtype/use-flow-type': 1,
    'flowtype/no-weak-types': 0,
    'flowtype/boolean-style': [2, 'boolean'],
    'flowtype/delimiter-dangle': 0,
    'flowtype/generic-spacing': 0,
    'flowtype/no-dupe-keys': 2,
    'flowtype/no-primitive-constructor-types': 0,
    'flowtype/object-type-delimiter': 0,
    'flowtype/require-parameter-type': 0,
    'flowtype/require-variable-type': 0,
    'flowtype/sort-keys': 0,
    'flowtype/union-intersection-spacing': 0,
    'flowtype/valid-syntax': 0,
  },
};
